---  
title: "Announcing SpIntro-Stats Web Applets"  
author: "Jim Robison-Cox and Allison Theobold, Montana State University"  
date: "October 13, 2015"  
---  

Software applications are an essential component of any simulation based inference (SBI) statistics course. At least two suites of web applets for introductory statistics currently exist (http://lock5stat.com/Statkey) and (http://rossmanchance.com/applets) and each allows public access. 
With the increasing interest in the simulation approach, we think it time for an open source software project focusing on SBI for introductory statistics which uses the interactive capabilities of web applications. We have begun a framework for such apps based on the Shiny web interface to R. We offer these to the SBI community for comment, feature requests, and collaboration.

The repository for the code is   
  [https://github.com/MTstateIntroStats/SpIntro-Stats.git](https://github.com/MTstateIntroStats/SpIntro-Stats.git)

### Running Spintro-Stats 
There are several ways to run the web apps:  

1) To check features without installing you can view it in this web page:  
     http://shiny.math.montana.edu/jimrc/IntroStatShinyApps/    
      Please do not send students to this site, as we can't handle hordes of users.   
      
2) To test on an individual computer running R (free and open source software):  
 * Install packages: ggplot2, gridExtra, shiny, shinythemes and their dependencies.   
 * Enter these commands into the R console:   
```
library(shiny)  
runGitHub("MTstateIntroStats/SpIntro-Stats")  
## Be patient. A browser window will appear with the app inside.  
## Use control-C in the R console to exit.  
```  

3) If you want to use these apps in a classroom setting, you'll need some IT expertise. Specifically,  a "Shiny server"
   which is free for academic purposes, from [https://www.rstudio.com/products/shiny/](https://www.rstudio.com/products/shiny/)    
   Be sure git is installed, and clone the code as in:   
```
git clone https://github.com/MTstateIntroStats/SpIntro-Stats.git  
```
Then you will have your own site to serve your own students.  

4) To get your own copy of the code, you need  "git" installed and a github account.  
Clone the repository  [https://github.com/MTstateIntroStats/SpIntro-Stats.git](https://github.com/MTstateIntroStats/SpIntro-Stats.git).  
   See a git tutorial for more instructions: https://help.github.com/


### Basic layout

To run the apps, the user has to choose the _Type_ of data to analyze:   

 * One Categorical,  
 * One Quantitative,   
 * Two Categorical,   
 * Two Quantitative,  or  
 * One of Each -- One Categorical & One Quantitative.  

The first option under each variable type is [Enter/Describe Data] which must be run before one can proceed to the next choices under each Variable Type: [Test] or [Estimate].

 * Testing is performed by sampling from the null model (One Categorical) or via permutation test (Two Categorical or One-of-Each) or by bootstrap (Two Quantitative).  The "One Quantitative" test of a single mean slides the data over to have the hypothesized mean, then resamples from the shifted distribution.

 * Confidence intervals are all based on bootstrap resamples. Plots show percentile intervals, but summary statistics are displayed for those who want to build _Estimate &#177; Multiplier * SE_ intervals (We do both).   

The apps also include 

 * a demo of confidence interval coverage (under "One Categ")  
 * an animated demo of the bootstrap process (under "One Quant"),  
 * demos of the effect of randomization on a "lurking" variable (under "One Categ" and "One Quant")  
 * "spinner" and "mixer" (balls drawn from a box) apps for generating random categorical variates (under "One Categ"), and  
 * z and t probability and quantile "look up" pages.  


### Contributing  

To correct errors or suggest features please use the google group: [https://groups.google.com/forum/#!forum/spintro-stats](https://groups.google.com/forum/#!forum/spintro-stats)

Suggestions are welcome, but given that this is a volunteer project, it might take some time to implement feature requests.  
If you would like to help with the project, the level of R programming needed is moderate. However, some knowledge of shiny, of html, and possibly of JavaScript is necessary.  

### Related Materials

We have also developed activities which utilize the web apps for a one semester statistics intro course. 
See our other github repository: [https://github.com/MTstateIntroStats/IntroStatActivities](https://github.com/MTstateIntroStats/IntroStatActivities) and [https://groups.google.com/forum/#!forum/mt-state-intro-stat-activities](its google group)



