
Modify Stat 216  MSU for Fall 2015
Incorporate text from Open Intro

Set one Quizork per week, one online graded HW as well.

Tu-thuRs sections

Checked calendar and syllabus.


* Unit 1 -- inference for 1 proportion  
** Day 1 activity -- Basic evaluation of a claim.  
  *** Fraud Detection  
  *** Syllabus  
  *** group discovery  
     plots/Act1-NullDist.png  
     D2L-1 - Working in groups
     
** Day 2 - Describe Distributions  
   Bring in Shiny App? - not yet
   mean -- median  
   sd -- IQR  
   outliers  
     plots/3classGradeCompareMn.png  
     plots/3classGradeCompareSkw.png  
     plots/3classGradeCompareSD.png  

**  TODone adapt Open Intro "Sample vs Population"
   parameter -- statistic  
   population -- sample  

** Day 3 -- Sampling  
   Uses Rossman-Chance Gettysburg app. I think that's OK.
   D2L-2 - sampling, more data description.
      
** Day 4 -- Helper- Hinderer -using Rossman-Chance Intro 2 p-value. 
  TODone:  Change ISI applet to shiny app -- also use a spinner? 
         Need to revisit after Cat-1 Test is working. 
     plots/Helper16.png  
     plots/StrOfEvidence-12Guesses.png  
     plots/pvalueStrengths.png  
   Q2 - DUI proportions Hyp test (not .5)
** Day 5 -- Hypothesis test 1 prop -- ESP
  TODone:  Change ISI applet to shiny app   
   plots/Zener_cards.png  
   plots/spinnerCircle.png  

  I took out the 3S summary.

   D2L-3 - Test Roulette Wheel, Why we like CI's.


** Day 6 -- Confidence interval  -- Rat Empathy  
  TODone:  Change ISI applet to shiny app   
   interval estimate preferred over point estimate
   bootstrap   intervals
   plots/trappedRat.png  
  Split off:  

** Day 7-  meaning of confidence
  TODO: need more work and perhaps a "story"
   Q3 - Gallop Poll Margin of Error. Meaning of "confidence"
 
** Day 8 -- example of 1 prop inference  - Male Idiot Theory
  TODone:  Change ISI applet to shiny app   
   margin of error
     plots/MIT-null.png  
   Q4 <- old Q7 - OKcupid CI for Blind Love Day, and comparing to 12.4%

** Day 9 -- Review  Kissing on rightside
     plots/kissing-null.png  
    D2L??

** Day 10 -- Exam Review followed by the exam:
  How do we handle those whose class is at 6:10 in giving the common
  hour?  Extend class with exam right afterwards?
  
Sept 22

* Unit 2 -- other situations  
** Day 10 -- Experiment vs Obs study  
   Some of Old Day 12 
   TODone: rebuild a lurking demo under 1 cat and 1 quant
   OpenIntro p 13-14 (sampling) 17-19 (Exp)
   Q8 - Exp vs Obs Study - OpenIntro S1.5 
** Day 11 -- Bootstrap CI to estimate single mean   
   Q9 - Why bootstrap?  Body Temp CI 
  TODO:  redo motivation and intro
  TODone: redo demo directions

** Day 12 -- Inference for Two proportions - Peanut Allergies 
   First use of "Report" of results.
   Q10 - Kick Cocaine habit w Desipramine Test p_1 - p_2

   
** Day 13 -- Test and Estimate the difference in 2 proportions  
   Use men/women and perception of weight in those who misjudge their
   weight.  "Bakery Smells" -> Quizork
   First use of "statistical significance"
   Quizork includes reading about RBANS and energy drinks
   Q11 - Wording of Pew's Obamacare question, bias from Voluntary response
 
** Day 14 -- Inference for 2 means -- Energy Drinks  
   Q12 - Sleeping Pills - hours slept, test: mu_1 = mu_2 (exp w/ placebo)

** Day 15 --Birth Weight
   Q13 - Compare Sitka Tree growth (Exp) 

** Day 16 -- Hyp Test 1 mean
    arsenic in toenails.
   ADD a bit about plausible values?

** Day 17 -- correlation / slope  
   a good reading on correlation & least squares?

** Day 18 -- test slope = 0

** Day 19 -- Errors  
   redo power -- what is the focus?

** Day 20 -- review  
   cutback - OK
   add regression example - Done
  and  Exam  Nov 3
* Unit 3 -- shortcut theoretical methods  

** Day 21 -- Normal and t Distributions  
   Uses new shiny web app

** Day 22 -- one proportion    - Z
   poor-2-fair college opinion, roulette,  kissing on right side, roshambo

** Day 23 -- two proportions    - Z

** Day 24 --  one mean  - t

** Day 25 --  two means - t + paired w/ energy drinks

**  --out -- Day 26 -- practice t based inference  Paired?


** -- out -- Day A1 -- Paired means 

** -- out -- Day A2 -- sample size effects  

** Day 27 -- Review  
  
---------------------------------------

Final exam
 

Graphics files
  
U1-D1.tex:  plots/Act1-NullDist.png 
U1-D2.tex:  plots/3classGradeCompareMn.png  
U1-D2.tex:  plots/3classGradeCompareSkw.png  
U1-D2.tex:  plots/3classGradeCompareSD.png  
U1-D4.tex:  plots/Helper16.png 
U1-D4.tex:  plots/StrOfEvidence-12Guesses.png 
U1-D4.tex:  plots/pvalueStrengths.png 
U1-D5.tex:  plots/Zener_cards.png 
U1-D5.tex:  plots/spinnerCircle.png 
U1-D6.tex:  plots/trappedRat.png 
U1-D7.tex:  plots/MIT-null.png 
U1-D8.tex:  plots/kissing-null.png 
U2-D10.tex: plots/IQ-shuffle.png 
U2-D10.tex: plots/SATprep-shuffles.png 
U2-D12.tex: plots/DolphinRandTest.png 
U2-D16.tex: plots/arsenicCIplot.png  
U2-D16.tex: plots/arsenicNullDistn.png  
U2-D18.tex: plots/attractiveAges.png 
U2-D18.tex: plots/spuriousCorr.png 
U2-D18.tex: plots/realCorr.png 


U2-D11.tex:  \includegraphics[width=.6\linewidth]{plots/OverWeightPropTest.png}
U2-D11.tex:  \includegraphics[width=.6\linewidth]{plots/rndomizedWeightMeans.png}
U2-D13.tex: \includegraphics[width=.9\linewidth]{plots/sleepDepBoxes.pdf}
U2-D13.tex: \includegraphics[width=.9\linewidth]{plots/sleepDepDots.pdf}
U2-D13.tex:\includegraphics[width=.9\linewidth]{plots/sleepHistogram.pdf}
U2-D13.tex:   \includegraphics[width=.5\linewidth]{plots/OneSleepDepTrial.png}
U2-D13.tex: \includegraphics[width=.8\linewidth]{plots/sleepDep-1000.png}
U2-D14.tex:  \includegraphics[width=.6\linewidth]{plots/DolphinRandTest.png}
U2-D14.tex:\includegraphics[width=\linewidth]{plots/pvalueStrengths.png}
U2-D15.tex:\includegraphics[width=\linewidth]{plots/plausibleProp.pdf}
U2-D15.tex:         \includegraphics[width=\linewidth]{plots/plausibleTemp.pdf}
U2-D16.tex:  \includegraphics[width=.7\linewidth]{plots/GilbertInstatKey.png}
U2-D18.tex:  \includegraphics[width=.7\linewidth]{plots/GilbertInstatKey.png}
U3-D27.tex:   \includegraphics[width=.8\linewidth]{plots/sample2.pdf}

   MScomp
 milkProtein.csv
vision.RData
reading.csv


Distracted While Driving:
 A Comparison of the Effects of Texting and Talking On a Cell Phone
Proceedings of the Human Factors and Ergonomics Society Annual
Meeting 
September 1, 2013 57: 1874-1878

@article{du2015randomized,
  title={Randomized trial of peanut consumption in infants at risk for peanut allergy},
  author={Du Toit, George and Roberts, Graham and Sayre, Peter H and Bahnson, Henry T and Radulovic, Suzana and Santos, Alexandra F and Brough, Helen A and Phippard, Deborah and Basting, Monica and Feeney, Mary and others},
  journal={New England Journal of Medicine},
  volume={372},
  number={9},
  pages={803--813},
  year={2015},
  publisher={Mass Medical Soc}
}

Pagination:

cover page
  BLANK back
calendar
Unit 1 page numbers 1-53                page numbered 32 gets color.
  starts on a back, ends on a front.
Unit 2 Divider - blue paper
  BLANK (in document)
  ADD 6 pages from "Open Intro"
Unit 2 page numbers 56 to  118
    starts on a back, ends on a front.
Unit 3 Divider - blue paper
  BLANK (in document)
Unit 3 page numbers 121 to 170


  pdfjam TR-raw.pdf '1-57' ../../isrs1-Experiments-2.pdf '1-'
  ../../isrs1-Experiment3.pdf '1-' TR-raw.pdf '58-' --outfile
  ../TR-completeCP

(then rename to give pdf suffix)

